### ISSUE TITLE
作者大佬有TG联系方式吗

### ISSUE THREAD

**Issue by xihaxz** [jat001/docker-sspanel-uim#1]
如题 想请教作者 有什么途径吗

**Comment by jat001** [comment]
有问题可以提issue，只回复有价值的问题，不提供一对一指导

**Comment by xihaxz** [comment]
> 有问题可以提issue，只回复有价值的问题，不提供一对一指导

我想问下大佬这个文档还有细化的可能吗？  对于Docker初学者来说有点难~~~~

**Comment by jat001** [comment]
不好意思，个人自用项目，readme 写给有相关基础知识的人，不面向初学者

**Comment by xihaxz** [comment]
> 不好意思，个人自用项目，readme 写给有相关基础知识的人，不面向初学者

好的，那我再自己研究研究吧
